import Link from "next/link";
import type { Locale } from "../../lib/i18n";
import { localizedPath } from "../../lib/i18n";
import { pageMetadata } from "../../lib/site";

const copy = {
  zh: { label:"实习经历", title:"英飞凌科技（新加坡）", lead:"混合信号设计工程师 · 全职实习", role:"混合信号设计工程师", place:"新加坡 · 2026.06–2027.04", work:"正在参与能量收集芯片设计，芯片可在 0.1 V 输入电压下启动并工作。项目目前仍在进行中。", status:"项目状态", wip:"进行中", public:"项目方向", private:"工作内容", publicScope:"能量收集芯片", privateScope:"低电压启动与工作电路设计", note:"本页介绍项目方向与启动、工作电压；内部电路架构及详细仿真、测试数据不在此展示。", projects:"查看个人项目", meta:"郜周豪在英飞凌科技（新加坡）担任混合信号设计工程师，参与可在 0.1 V 下启动并工作的能量收集芯片项目。" },
  en: { label:"Experience", title:"Infineon Technologies Singapore", lead:"Mixed-Signal Design Engineer · Full-time internship", role:"Mixed-Signal Design Engineer", place:"Singapore · 2026.06–2027.04", work:"Currently working on an energy-harvesting chip that can start up and operate at an input voltage of 0.1 V. The project is ongoing.", status:"Status", wip:"In progress", public:"Project", private:"Work focus", publicScope:"Energy-harvesting chip", privateScope:"Low-voltage startup and operating circuits", note:"This page describes the project and its startup and operating voltage. Internal circuit architecture and detailed simulation or measurement data are not shown.", projects:"View personal projects", meta:"Gao Zhouhao’s mixed-signal design internship at Infineon, working on an energy-harvesting chip that starts up and operates at 0.1 V." },
} as const;
export const metadata = pageMetadata("实习经历", copy.zh.meta, "/experience", "zh");
export function ExperiencePage({locale}:{locale:Locale}) { const t=copy[locale]; return <main id="main-content" className="page-shell" lang={locale==="zh"?"zh-CN":"en"}><p className="eyebrow">{t.label}</p><h1 className="page-title">{t.title}</h1><p className="lead" style={{marginTop:"1.5rem"}}>{t.lead}</p><section className="section split"><div><p className="eyebrow">2026.06 — 2027.04</p><h2 className="section-heading">{t.role}</h2><p className="section-intro">{t.place}</p><p className="section-intro">{t.work}</p></div><dl className="fact-panel"><dt>{t.status}</dt><dd>{t.wip}</dd><dt>{t.public}</dt><dd>{t.publicScope}</dd><dt>{t.private}</dt><dd>{t.privateScope}</dd></dl></section><p className="status-note section">{t.note}</p><div className="button-row"><Link className="button" href={localizedPath("/projects",locale)}>{t.projects}</Link></div></main> }
export default function Page(){return <ExperiencePage locale="zh"/>}
