import type { Locale } from "../../../lib/i18n";
import styles from "./page.module.css";
const source = "https://github.com/gaozhouhao/npu/blob/a41c2339cfcd8ec40181b069b3aeacb39e6c64b5/";

export default function ResnetUpdates({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className={styles.section} aria-labelledby="npu-resnet">
    <div className={styles.sectionTitle}><h2 id="npu-resnet">{zh ? "ResNet-8：量化扩展与模型编译" : "ResNet-8: quantization and model compilation"}</h2><span>2026-10-11</span></div>
    <p className={styles.finding}>{zh ? "在原有 GEMM、卷积和 C SRAM 通路上，我增加了逐通道量化、四槽参数缓存、残差加法和全局平均池化，并编写 TFLite 编译器，将 ResNet-8 转换为可直接执行的任务描述符。" : "Building on GEMM, convolution and C SRAM, I added per-channel quantization, a four-slot parameter bank, residual addition and global average pooling. A TFLite compiler translates ResNet-8 into executable descriptors."}</p>
    <div className={styles.updateGrid}>
      <article><span className={styles.version}>PER-CHANNEL QUANTIZATION</span><h3>{zh ? "四路独立量化参数" : "Independent parameters for four lanes"}</h3><p>{zh ? "每个输出通道分别使用 Bias、Multiplier 和 Shift，保留四路 INT32→INT8 后处理。输入 Zero Point 修正离线折叠进 Bias；ReLU 以输出 Zero Point 为截断阈值。原有 MNIST Per-tensor 模式保留。" : "Each output channel has its own bias, multiplier and shift, with four parallel INT32-to-INT8 lanes. Input zero-point correction is folded into bias offline; ReLU clamps at the output zero point. The MNIST per-tensor mode is retained."}</p></article>
      <article><span className={styles.version}>PARAMETER SLOT BANK</span><h3>{zh ? "参数与部分和按 Slot 对应" : "Parameters paired with partial-sum slots"}</h3><p>{zh ? "四个物理 Slot 各缓存四通道参数，通过 Valid/Tag 标识 N Tile。参数缓存与 C SRAM 独立存储、共用 Slot 编号；在最终 C Tile 写回 DDR 后释放，支持多 K、多 N 分块和 A Reuse。" : "Four physical slots each cache four-channel parameters, with valid bits and N-tile tags. The parameter bank and C SRAM are separate memories sharing slot IDs. Retirement follows final C-tile DDR writeback, supporting multi-K, multi-N tiling and A reuse."}</p></article>
    </div>
    <details className={styles.details}><summary>{zh ? "参数 Slot 结构与压力测试" : "Parameter slots and stress testing"}</summary>
      <div className={styles.tableScroll} tabIndex={0} role="region" aria-label={zh ? "参数与部分和 Slot 对应关系" : "Parameter and partial-sum slot mapping"}><table className="result-table"><thead><tr><th>Slot</th><th>C SRAM</th><th>Parameter Bank</th></tr></thead><tbody>{[0,1,2,3].map(i => <tr key={i}><th scope="row">{i}</th><td>4×4 INT32 Partial Sum</td><td>4×(Bias, Multiplier, Shift)</td></tr>)}</tbody></table></div>
      <p className={styles.finding}>{zh ? "Fill → Valid/Tag 命中 → 最后一段 K 完成 → Requantization → DDR Writeback → Retire。中间 K Tile 只累加 INT32 部分和，不提前量化。" : "Fill → valid/tag match → final K tile completes → requantization → DDR writeback → retire. Intermediate K tiles only accumulate INT32 partial sums."}</p>
      <p className={styles.note}>{zh ? "M=8、N=32、K=32、K_TILE_SIZE=16，覆盖 16 个输出 Tile、256 个 INT8 元素。实测记录中 Baseline、PSUM、PSUM + A Reuse 三种配置均 PASS；以下为 PSUM 配置，不用于模式间性能比较。" : "M=8, N=32, K=32, K_TILE_SIZE=16: 16 output tiles and 256 INT8 elements. Reported Baseline, PSUM and PSUM + A Reuse tests all pass. The record below is for PSUM only, not a performance comparison between modes."}</p>
      <pre className={styles.compactCode}>PARAM SLOT STRESS PASS{"\n"}cycles=1871  reads=848  writes=64{"\n"}fills=16  retires=16  psum_rows=128  acc00=-11  busy=0</pre>
      <p className={styles.note}><a href={source + "rtl/core/output_param_slot_bank.sv"}>Parameter Slot RTL ↗</a> · <a href={source + "sim/tb/param_slot_stress_npu_tb.sv"}>Stress TB ↗</a> · <a href={source + "scripts/run_param_slot_stress.sh"}>{zh ? "三配置测试脚本" : "Three-configuration test script"} ↗</a></p>
    </details>
    <details className={styles.details}><summary>{zh ? "量化公式、卷积与新增算子" : "Quantization, convolution and new operators"}</summary>
      <p className={styles.note}>{zh ? "逐通道重量化与输入 Zero Point 的 Bias 补偿：" : "Per-channel requantization and input zero-point bias correction:"}</p><pre className={styles.compactCode}>qY,c = sat8(Round((acc_c + b′c) × Mc / 2^Rc) + ZY){"\n"}b′c = bc − ZA × Σk Wc,k</pre>
      <p className={styles.note}>{zh ? "Conv Patch Loader 支持量化 Padding Zero Point 与 TFLite SAME 的不对称边界。Padding 直接生成输入 Zero Point，不读取 DDR，仍采用隐式 im2col。Pool2D 增加 Global Average Pooling，保留 Max Pooling。" : "The patch loader supports the quantized padding zero point and asymmetric TFLite SAME boundaries. Padding is generated without DDR reads, retaining implicit im2col. Pool2D adds global average pooling while preserving max pooling."}</p>
      <p className={styles.finding}>{zh ? "Residual Add 使用 Opcode 0x05，从 DDR 读取两个 INT8 Tensor，处理各自 Scale/Zero Point 后合并到输出量化域。算术部分四路并行，DDR 读写当前串行执行，尚未优化带宽与流水吞吐。" : "Residual Add uses opcode 0x05 to read two INT8 tensors and combine their scales and zero points in the output domain. Arithmetic runs across four lanes; DDR reads and writes remain serial, without bandwidth or pipeline optimization."}</p><pre className={styles.compactCode}>qY ≈ sat8(Round(((qA − ZA)MA + (qB − ZB)MB) / 2^R) + ZY)</pre>
      <p className={styles.note}><a href={source + "rtl/compute/postprocess_unit.sv"}>Postprocess RTL ↗</a> · <a href={source + "rtl/core/residual_add_engine.sv"}>Residual Add RTL ↗</a></p>
    </details>
    <div className={styles.sectionTitle} style={{marginTop:"1.5rem"}}><h3>{zh ? "TFLite → 14 条硬件描述符" : "TFLite → 14 hardware descriptors"}</h3></div>
    <p className={styles.note}>{zh ? "编译器解析 MLPerf Tiny ResNet-8 的 Tensor、算子、权重和量化参数，完成权重重排、Bias Folding、整数 Multiplier/Shift 编译和 DDR 地址分配。残差中间 Tensor 保留，Reshape 作为内存别名；分类阶段跳过 Softmax，直接从 logits 取 Top-1。" : "The compiler parses MLPerf Tiny ResNet-8 tensors, operators, weights and quantization parameters, then performs weight reordering, bias folding, integer multiplier/shift generation and DDR allocation. Residual tensors are retained and reshape becomes a memory alias. Classification bypasses softmax and selects Top-1 from logits."}</p>
    <div className={styles.descriptorStrip}><span>9 Conv2D<small>{zh ? "含 Projection" : "Including projection"}</small></span><span>3 Residual Add</span><span>1 Global AvgPool</span><span>1 Fully Connected</span></div>
    <p className={styles.note}>ddr.bin · ddr.hex · descriptors.bin · manifest.json · <a href={source + "scripts/compile_resnet8_tflite.py"}>{zh ? "编译器源码" : "Compiler source"} ↗</a></p>
    <div className={styles.runResult}><h3>{zh ? "首次 ResNet-8 整网 RTL 功能运行" : "First end-to-end ResNet-8 RTL functional run"}</h3><p>{zh ? "采用默认量化零输入，完成 14 条描述符并输出 10 个 INT8 分类分数。尚未做真实 CIFAR-10 图像测试或 TFLite Golden 比对，因此不作为模型数值正确性验证。" : "Using the default quantized-zero input, the run completes 14 descriptors and produces 10 INT8 scores. Real CIFAR-10 images and a TFLite golden comparison have not yet been tested; this is not a model numerical-correctness validation."}</p>
      <div className={styles.metrics}><div><strong>1,828,229</strong><span>Cycles</span></div><div><strong>1,279,718</strong><span>AXI Read Beats</span></div><div><strong>28,700</strong><span>AXI Write Beats</span></div><div><strong>0</strong><span>Busy</span></div></div>
      <p className={styles.note}>{zh ? "该工作负载与 MNIST 不同，不与上面的 MNIST 周期直接计算加速比。" : "This workload differs from MNIST; these cycle counts are not used to calculate a speedup against the MNIST results above."}</p>
      <details className={styles.details}><summary>{zh ? "输出、测试条件与源码" : "Output, test conditions and sources"}</summary><pre className={styles.compactCode}>logits = [33, 3, 7, 25, 33, 9, 31, 14, 22, 8]{"\n"}top1 = 0</pre><p className={styles.note}>{zh ? "类别 0 与 4 同为最大值 33，Testbench 选取先出现的类别 0。输入填充输入 Zero Point，代表实数零。仓库 run_resnet8.sh 默认执行基线配置，未开启 PSUM/A Reuse 实验宏。性能和 PASS 数字来自本阶段提供的运行记录；此次网站更新核对源码，未重新运行 RTL。" : "Classes 0 and 4 tie at 33; the testbench selects the first, class 0. Inputs are filled with the input zero point, representing real zero. The repository run_resnet8.sh uses the baseline configuration without PSUM/A Reuse experimental macros. Performance and PASS figures come from the supplied run records; source was checked, but RTL was not rerun for this website update."}</p><p className={styles.note}><a href={source + "sim/tb/resnet8_npu_tb.sv"}>ResNet-8 TB ↗</a> · <a href={source + "scripts/run_resnet8.sh"}>Run script ↗</a> · <a href="https://github.com/gaozhouhao/npu/commit/a41c2339cfcd8ec40181b069b3aeacb39e6c64b5">a41c233 ↗</a></p></details>
    </div>
  </section>;
}
